### PR TITLE
Delete most popular and commented page

### PR DESCRIPTION
**Pull request by OttlikG**
We want to migrate away from Keen so we remove the routes that's using it.

https://docs.google.com/document/d/1jFIF_vwmZUWj4MSJf2idiurOt3TtUhUsXZWbV23Ykk0/edit?ts=5bfbd999#

### CODE REVIEW

**Comment by ddigulescu** [comment]
awesome 👍, if it works locally let's see what happens in test env after merge. The keen-query bits should also be removed from `https://github.com/Financial-Times/alphaville-es-interface-service`

**Comment by OttlikG** [comment]
Yes I removed those: https://github.com/Financial-Times/alphaville-es-interface-service/pull/5

**Comment by umbobabo** [comment]
@ddigulescu @OttlikG It would be good release this before the end of the day, let me know if I can help with something.

**Comment by roland-vachter** [comment]
With the branching approach we are now using, I think it would make more sense to merge to master first, then merge master into the `migration_off_wordpress` branch.

**Comment by edds** [comment]
This PR is being closed due to inactivity as part of a Pull Request Bankruptcy. If you feel it’s still useful or relevant please feel free to re-open it.

**Pull request closed without merging**
